apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-go-vtmefgfc
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/backend-tests-go-vtmefgfc:f80d16de76853210f7cb909dba597bf680036db5@sha256:dd315e43984a3daf343b8dc80190a5901280ae6ecbe5fc01ad9e8d68720c2adf
          name: container-image
